# Generated by Django 3.2.9 on 2021-12-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0002_auto_20211215_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list',
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ManyToManyField(related_name='tasks', to='proj_app.TaskList'),
        ),
    ]
