# Generated by Django 3.2.9 on 2021-12-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0004_auto_20211227_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dailyTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='proj_app.dailytask'),
        ),
    ]
