# Generated by Django 3.2.9 on 2021-12-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0005_alter_task_dailytask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='list',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
